# Generated by Django 5.2.4 on 2025-08-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='discription',
            field=models.TextField(default=''),
        ),
    ]
